
#user  nobody;
#worker_processes  1;

#error_log  logs/error.log;
#error_log  logs/error.log  notice;
#error_log  logs/error.log  info;

#pid        logs/nginx.pid;


    server {
        listen       80;
         server_name  jujiashizhi-admin.nurseadvicetest.xyz;  # 如果没有域名可以改成ip
        #server_name  127.0.0.1;  # 如果没有域名可以改成ip
        #server_name jujiashizhi-admin.nurseadvicetest.top;

        #charset koi8-r;

        #access_log  logs/host.access.log  main;

        location / {
            root   /htdocs/jujiashizhi/admin/dist;
            index  index.html index.htm;
        }

		location /admin {
			       proxy_pass https://jujiashizhi-api.nurseadvicetest.xyz/admin/; # 默认是443 端口号，可以改成ip + 端口号
			       #proxy_pass https://jujiashizhi-api.nurseadvicetest.top/admin/; # 默认是443 端口号，可以改成ip + 端口号
			       #proxy_pass https://127.0.0.1/admin/; # 默认是443 端口号，可以改成ip + 端口号
		}
        #error_page  404              /404.html;

        # redirect server error pages to the static page /50x.html
        #
        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   html;
        }

    }


    #HTTPS server
    
    server {
        listen       443 ssl;
        server_name  jujiashizhi-api.nurseadvicetest.xyz;  # 可以改为ip
        #server_name   jujiashizhi-api.nurseadvicetest.top;  # 可以改为ip
        #server_name   127.0.0.1;  # 可以改为ip
        root         /htdocs/jujiashizhi/api/public;
        index        index.php index.html index.htm;

		client_max_body_size 200m; 
		fastcgi_read_timeout 600;
		#ssl_certificate /etc/nginx/cert/jujiashizhi-api.nurseadvicetest.top_nginx/jujiashizhi-api.nurseadvicetest.top.pem;  # 这行和下一行是域名的授权信息，从与服务器域名哪里下载，让后放在对应位置
        ssl_certificate /etc/nginx/cert/jujiashizhi-api.nurseadvicetest.xyz_nginx/jujiashizhi-api.nurseadvicetest.xyz_bundle.pem;
    	#ssl_certificate_key /etc/nginx/cert/jujiashizhi-api.nurseadvicetest.top_nginx/jujiashizhi-api.nurseadvicetest.top.key;
        ssl_certificate_key /etc/nginx/cert/jujiashizhi-api.nurseadvicetest.xyz_nginx/jujiashizhi-api.nurseadvicetest.xyz.key;
    	ssl_session_timeout 5m;
    	ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
    	ssl_ciphers ECDHE-RSA-AES128-GCM-SHA256:HIGH:!aNULL:!MD5:!RC4:!DHE;
    	ssl_prefer_server_ciphers on;

		gzip on;
    	gzip_min_length 1k;
    	gzip_buffers 4 16k;
    	gzip_comp_level 2;
    	gzip_vary off;
    	gzip_disable "MSIE [1-6]\.";


    	location / {
        	try_files $uri $uri/ /index.php?$query_string;
        	if (!-e $request_filename) {
                rewrite  ^(.*)$  /index.php?s=$1  last;
                break;  
        	}
    	}


        #charset koi8-r;

        #access_log  logs/host.access.log  main;


        #error_page  404              /404.html;

        # redirect server error pages to the static page /50x.html
        #
        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   html;
        }



        # proxy the PHP scripts to Apache listening on 127.0.0.1:80
        #
        #location ~ \.php$ {
        #    proxy_pass   http://127.0.0.1;
        #}

        # pass the PHP scripts to FastCGI server listening on 127.0.0.1:9000
        #
		location ~ \.php$ {
            root           /htdocs/jujiashizhi/api/public;
        	fastcgi_pass   php:9000;
        	fastcgi_index  index.php;
        	include        fastcgi_params;
        	fastcgi_param  SCRIPT_FILENAME  $document_root$fastcgi_script_name;


        	set $path_info "";
        	set $real_script_name $fastcgi_script_name;
        	if ($fastcgi_script_name ~ "^(.+?\.php)(/.+)$") {
             	 set $real_script_name $1;
             	set $path_info $2;
        	}
        	fastcgi_param SCRIPT_NAME $real_script_name;
        	fastcgi_param PATH_INFO $path_info;
    	}

    }
