server {
    listen       80;
    server_name  jujiashizhi-admin.syncsmart.cn;
    root         /htdocs/jujiashizhi/admin/dist;
    index	 index.php index.html index.htm;

    client_max_body_size 20m;
    fastcgi_read_timeout 600;

    gzip on;
    gzip_min_length 1k;
    gzip_buffers 4 16k;
    gzip_comp_level 2;
    gzip_vary off;
    gzip_disable "MSIE [1-6]\.";

    location / {
        try_files $uri $uri/ /index.php?$query_string;
        if (!-e $request_filename) {
                rewrite  ^(.*)$  /index.php?s=$1  last;
                break;
        }
    }

    location /admin {
       proxy_pass https://jujiashizhi-api.syncsmart.cn/admin/;
    }
}

server {
    listen       80;
    server_name  jujiashizhi.syncsmart.cn;
    root         /htdocs/jujiashizhi/h5/unpackage/dist/build/h5;
    index        index.html index.htm;

    client_max_body_size 10000M;
    fastcgi_read_timeout 600;

    gzip on;
    gzip_min_length 1k;
    gzip_buffers 4 16k;
    gzip_comp_level 2;
    gzip_vary off;
    gzip_disable "MSIE [1-6]\.";

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /api {
       proxy_pass https://jujiashizhi-api.syncsmart.cn/api/;
    }
}

server {
    listen       443 ssl;
    server_name  jujiashizhi-api.syncsmart.cn;
    root         /htdocs/jujiashizhi/api/public;
    index        index.php index.html index.htm;

    client_max_body_size 20m;
    fastcgi_read_timeout 600;

    ssl_certificate /etc/nginx/cert/jujiashizhi-api.syncsmart.cn/jujiashizhi-api.syncsmart.cn_chain.crt;
    ssl_certificate_key /etc/nginx/cert/jujiashizhi-api.syncsmart.cn/jujiashizhi-api.syncsmart.cn_key.key;
    ssl_session_timeout 5m;
    ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
    ssl_ciphers ECDHE-RSA-AES128-GCM-SHA256:HIGH:!aNULL:!MD5:!RC4:!DHE;
    ssl_prefer_server_ciphers on;

    gzip on;
    gzip_min_length 1k;
    gzip_buffers 4 16k;
    gzip_comp_level 2;
    gzip_vary off;
    gzip_disable "MSIE [1-6]\.";


    location / {
        try_files $uri $uri/ /index.php?$query_string;
        if (!-e $request_filename) {
                rewrite  ^(.*)$  /index.php?s=$1  last;
                break;
        }
    }

    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        #rewrite (.*) https://www.xiaocx.org$1;
    }

    location ~ \.php$ {
        fastcgi_pass   127.0.0.1:9000;
        fastcgi_index  index.php;
        fastcgi_param  SCRIPT_FILENAME  $document_root$fastcgi_script_name;
        include        fastcgi_params;


        set $path_info "";
        set $real_script_name $fastcgi_script_name;
        if ($fastcgi_script_name ~ "^(.+?\.php)(/.+)$") {
             set $real_script_name $1;
             set $path_info $2;
        }
        fastcgi_param SCRIPT_NAME $real_script_name;
        fastcgi_param PATH_INFO $path_info;
    }
}
